### ISSUE TITLE
fastgron add header option for Auth

### ISSUE THREAD

**Issue by n4n0r** [adamritter/fastgron#13]
Hi,

Great project.

Suggestion: add an option to fastgron to specify a header, such as an Authentication header for exemple, so you can use it with authenticated APIs.

Thanks !

Ronan

**Comment by adamritter** [comment]
Thanks for the suggestion!

I implemented it in
https://github.com/adamritter/fastgron/tree/v0.6.4

It should soon be available on homebrew as well.
