### ISSUE TITLE
fastgron emits File not found for "https://api.github.com/repos/adamritter/fastgron/commits"

### ISSUE THREAD

**Issue by ghost** [adamritter/fastgron#7]
// compare gron result with fastgron result

$ gron "https://api.github.com/repos/adamritter/fastgron/commits" | head -3
json = [];
json[0] = {};
json[0].author = {};

$ fastgron "https://api.github.com/repos/adamritter/fastgron/commits"      
File not found: https://api.github.com/repos/adamritter/fastgron/commits

**Comment by adamritter** [comment]
Thanks, it was a regression, fixed in 0.4.13
